### ISSUE TITLE
Different trained models with the same configuration (rules and xrf package)

### ISSUE THREAD

**Issue by frequena** [tidymodels/rules#10]
Hello, I have used `rules` package to create a rulefit model. But I do not manage to replicate it with the `xrf` package. I'm not specifying any hyperparameter neither rules nor xrf model.

In fact, these two models are quite different from each other. For instance, the rules package has 138 rules and the xrf package has 340. Besides, the output retrieved of two made-up observations is completely different as well.

Thank you for your work!

```r

library(parsnip)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(rules)
library(mlbench)
library(xrf)

data(Ionosphere)

Ionosphere <- Ionosphere %>% select(V3, V4, V5, Class)

model_parsnip <- rule_fit() %>%
    set_mode('classification') %>%
    set_engine('xrf') %>%
    fit(Class ~ ., data = Ionosphere)


model_no_parsnip <- xrf(Class ~ .,
                     data = Ionosphere,
                     family = "binomial")

test_df <- tibble('V3' = c(1, 0), 'V4' = c(1,-0.5), 'V5' = c(0.3, 0.9))

model_parsnip
#> parsnip model object
#> 
#> Fit time:  3.2s 
#> An eXtreme RuleFit model of 138 rules.
#> 
#> Original Formula:
#> 
#> Class ~ V3 + V4 + V5
model_no_parsnip
#> An eXtreme RuleFit model of 340 rules.
#> 
#> Original Formula:
#> 
#> Class ~ V3 + V4 + V5

predict(model_parsnip, test_df, type = 'prob')
#> # A tibble: 2 x 2
#>   .pred_bad .pred_good
#>       <dbl>      <dbl>
#> 1     0.618      0.382
#> 2     0.696      0.304
predict(model_no_parsnip, test_df, type = 'response')
#>            1
#> 1 0.81670540
#> 2 0.01647708
```

<sup>Created on 2020-06-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

```

**Comment by topepo** [comment]
They use different defaults. See `?rules::xrf_fit` and `?xrf::xrf.formula`. I should definitely document this better. 

`rules::xrf_fit()` sets `lambda` for the glmnet` model whereas `xrf` does not (and I think let's `glmnet.cv()` figure it out). 

Also, since these models use a lot of random numbers, make sure that you set the seed before each model fit to make the results reproducible as well as using the same random numbers.

**Comment by topepo** [comment]
More explanations in 9e93ce3
