### ISSUE TITLE
Error: package or namespace load failed for ‘rules’:

### ISSUE THREAD

**Issue by wdkeyzer** [tidymodels/rules#45]
I've been successfully loading the rules library and running Cubist models until recently I keep getting this error message after `library(rules)`.

Error: package or namespace load failed for ‘rules’:
 .onLoad failed in loadNamespace() for 'rules', details:
  call: check_model_doesnt_exist(model)
  error: Model `cubist_rules` already exists

I've tried uninstalling and reinstalling the package without succes. What am I missing here? 

I'm running R version 4.1.2 (2021-11-01) -- "Bird Hippie" on platform: aarch64-apple-darwin20 (64-bit)

**Comment by juliasilge** [comment]
We have just recently done a parsnip release, along with releases for the parsnip extension packages, that changed how the models are registered. It seems like you have gotten into an awkward state! 😬 

As of right now, we are still waiting on the rules CRAN release so I would recommend installing both from GitHub if you are able via `devtools::install_github()`. If you are not able to install from GitHub, I would recommend installing rules from CRAN and the _last_ version of parsnip via `devtools::install_version("parsnip", version = "0.1.7")`.

This will get sorted out when the new version of rules gets to CRAN.

**Comment by juliasilge** [comment]
The new version of rules is now on CRAN. Let us know if you have further problems with installation! 🙌

**Comment by wdkeyzer** [comment]
yes ! 
it works again
thank you
