### ISSUE TITLE
`New names:` messages on `fit`

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/rules#59]
Had seen these while working on previous PRs and realized in #58 that they might be new since last CRAN release:

_Originally posted by @simonpcouch in https://github.com/tidymodels/rules/pull/58#discussion_r886740035_

**Comment by simonpcouch** [comment]
Closed in https://github.com/holub008/xrf/pull/21. :)

**Comment by simonpcouch** [comment]
Reopening as a reminder to regenerate docs + snapshots and make sure we've gotten rid of any relevant `suppressMessages` calls once the new xrf release is out.

**Comment by EmilHvitfeldt** [comment]
this has been fixed now :)
