### ISSUE TITLE
Lots of "New name:"

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/rules#61]
Having looked everywhere, but in `test-rule-fit-regression.R` at least, I see a lot of this, which properly isn't too hard to remove

New names:
* `.` -> `....1`
* `.` -> `....2`
* `.` -> `....3`
* `.` -> `....4`
* `.` -> `....5`
* `.` -> `....6`
* `.` -> `....7`
* `.` -> `....8`
* `.` -> `....9`
* `.` -> `....10`
* `.` -> `....11`
* `.` -> `....12`
* `.` -> `....13`
* `.` -> `....14`
* `.` -> `....15`
* `.` -> `....16`
* `.` -> `....17`
* `.` -> `....18`
* `.` -> `....19`

**Comment by juliasilge** [comment]
Related to #59 and the fix in xrf, I believe?

**Comment by EmilHvitfeldt** [comment]
You are right, I'll close this issue!
