### ISSUE TITLE
Caculation is slow in tidymodels-rules compared with caret-cubist

### ISSUE THREAD

**Issue by gglee4ai** [tidymodels/rules#7]
I am a beginner in both caret and tidymodels and trying to adapt tidymodels-rules to my analysis.

When using doParallel pkg, I realized that the caret-cubist calculates much faster than the tidymodels-cubist. Is there a special reason of speed difference between them?
I guest the basic engine in two frameworks are similar.

The link is a basic tutorial and I attached doParallel chunk and adapted to make the same training condition:
[caret vs tidymodels example](https://konradsemsch.netlify.app/2019/08/caret-vs-tidymodels-comparing-the-old-and-new)

**Comment by topepo** [comment]
"slow" is a subjective assessment. Do you have any benchmarking on this? That would be very helpful. 

Keep in mind that, currently. the parallelization is done different between the two packages (tidymodels/tune#16) so it it's really an apples-to-apples comparison.

**Comment by gglee4ai** [comment]
Thanks for your kind reply.
I attached a R code to compare rules with caret.
[caret_vs_rules.R](https://raw.githubusercontent.com/gglee4ai/public/master/caret_vs_rules.R)

Please check results.
In my computer,
caret: 1.6 mins
rules: 10 mins

I am not sure why this is so different

**Comment by gglee4ai** [comment]
```r
## setting
library(tidyverse)
library(tidymodels)
library(rules)
library(caret)
library(doParallel)

all_cores <- parallel::detectCores(logical = FALSE)
clusters <- makeForkCluster(all_cores)
registerDoParallel(clusters)
foreach::getDoParWorkers()
df <- read_csv("https://raw.githubusercontent.com/gglee4ai/public/master/df_test_rules.csv")


## caret
caret_grid <- expand.grid(
  .committees = c(1, seq(5, 100, by = 5)),
  .neighbors = c(1, 3, 4, 5, 6, 7)
)
caret_ctrl <- trainControl(
  method = "repeatedcv",
  repeats = 3,
  number = 10
)

start_time <- Sys.time()
caret_mod <- train(TTS ~ .,
  data = df,
  method = "cubist",
  tuneGrid = caret_grid,
  trControl = caret_ctrl
)
stop_time <- Sys.time()
caret_time <- stop_time - start_time 


## rules
rules_grid <-
  caret_grid %>% 
  rename(committees = .committees,
         neighbors = .neighbors)

rules_folds <- vfold_cv(df, v = 10, repeats = 3)

rules_mod <-
  cubist_rules(neighbors = tune(), committees = tune()) %>% 
  set_engine("Cubist")

start_time <- Sys.time()
rules_tune <-
  rules_mod %>% 
  tune_grid(TTS ~ .,
            resamples = rules_folds, 
            grid = rules_grid)
rules_tune
stop_time <- Sys.time()
rules_time <- stop_time - start_time 


## results
cat("caret: ", caret_time, "mins")
cat("rules: ", rules_time, "mins")


## close
stopCluster(clusters)
```

**Comment by topepo** [comment]
That is mostly likely due to the differences in how we parallel process. `tune` parallelizes over resamples and `caret` parallelizes over resamples and tuning parameters. We're changing that in `tune` soon (tidymodels/tune#16).
